### ISSUE TITLE
Can this implementation work as a drop-in substitute for LSTM layer?

### ISSUE THREAD

**Issue by ianni67** [malcolmw/LTCNN#1]
Hello, thank you very much for sharing your work.
As I've just started investigating liquid networks, my question is, as reported in the title:  Can this implementation work as a drop-in substitute for LSTM layer?
Thank you very much for your kind help

**Comment by malcolmw** [comment]
Hi @ianni67, yes this can be used as a drop-in replacement for LSTM layers but I recommend you look at the repository here https://github.com/mlech26l/ncps from the original authors.
